# Generated by Django 5.1.4 on 2025-01-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_fotografia_usuario_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebula', 'NEBULOSA'), ('ESTRELA', 'Star'), ('Galaxy', 'GALÁXIA'), ('PLANETA', 'Planet')], default='', max_length=100),
        ),
    ]
