# Generated by Django 5.1.4 on 2025-02-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebula', 'NEBULOSA'), ('ESTRELA', 'Star'), ('GALÁXIA', 'Galaxy'), ('Planet', 'PLANETA')], default='', max_length=100),
        ),
    ]
