# Generated by Django 5.1.4 on 2025-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebula'), ('Star', 'ESTRELA'), ('GALÁXIA', 'Galaxy'), ('Planet', 'PLANETA')], default='', max_length=100),
        ),
    ]
