# Generated by Django 5.1.4 on 2024-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebula'), ('Star', 'ESTRELA'), ('Galaxy', 'GALÁXIA'), ('Planet', 'PLANETA')], default='', max_length=100),
        ),
    ]
