# Generated by Django 5.1.4 on 2025-01-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_categoria_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebula'), ('ESTRELA', 'Star'), ('Galaxy', 'GALÁXIA'), ('Planet', 'PLANETA')], default='', max_length=100),
        ),
    ]
